"""initial

Revision ID: 3bd54c418660
Revises:
Create Date: 2026-06-12 14:39:52.960558

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd54c418660"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blood_glucose",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "measured_at", name="uq_blood_glucose_user_measured_at"
        ),
    )
    with op.batch_alter_table("blood_glucose", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_blood_glucose_measured_at"), ["measured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blood_glucose_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "blood_pressure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("systolic", sa.Integer(), nullable=False),
        sa.Column("diastolic", sa.Integer(), nullable=False),
        sa.Column("pulse", sa.Integer(), nullable=True),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "measured_at", name="uq_blood_pressure_user_measured_at"
        ),
    )
    with op.batch_alter_table("blood_pressure", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_blood_pressure_measured_at"), ["measured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blood_pressure_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "ketones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "measured_at", name="uq_ketones_user_measured_at"
        ),
    )
    with op.batch_alter_table("ketones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ketones_measured_at"), ["measured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ketones_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ketones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ketones_user_id"))
        batch_op.drop_index(batch_op.f("ix_ketones_measured_at"))

    op.drop_table("ketones")
    with op.batch_alter_table("blood_pressure", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blood_pressure_user_id"))
        batch_op.drop_index(batch_op.f("ix_blood_pressure_measured_at"))

    op.drop_table("blood_pressure")
    with op.batch_alter_table("blood_glucose", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blood_glucose_user_id"))
        batch_op.drop_index(batch_op.f("ix_blood_glucose_measured_at"))

    op.drop_table("blood_glucose")
    # ### end Alembic commands ###
